name: Verify Locator Every Hour

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Ejecutar cada hora
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ChromeDriver
        run: |
          LATEST=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Asegúrate de especificar la versión de Python correcta

      - name: Install dependencies
        run: |
          pip install selenium
          pip install requests

      - name: Run script
        run: python main.py
