name: Verify Locator Every Hour

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Ejecutar cada hora
  
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Chromedriver URL
        id: chromedriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
          CHROMEDRIVER_URL=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          echo "::set-output name=chromedriver_url::https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_URL}/chromedriver_linux64.zip"
        shell: bash

      - name: Set up ChromeDriver
        run: |
          wget ${{ steps.chromedriver.outputs.chromedriver_url }}
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          mv chromedriver /usr/local/bin/
        shell: bash


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Asegúrate de especificar la versión de Python correcta

      - name: Install dependencies
        run: |
          pip install selenium
          pip install requests

      - name: Run script
        run: python main.py
